// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wphnvujuebfylacchrfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwaG52dWp1ZWJmeWxhY2NocmZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNTAxOTYsImV4cCI6MjA3MjkyNjE5Nn0.JVrVyo_qGjkVOq5V7l3HxdqZfLgA4UvxLLxu2YAmMYs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});